apiVersion: v1
items:
- apiVersion: elasticsearch.k8s.elastic.co/v1
  kind: Elasticsearch
  metadata:
    annotations:
      eck.k8s.elastic.co/orchestration-hints: '{"no_transient_settings":true,"service_accounts":true}'
      elasticsearch.k8s.elastic.co/cluster-uuid: NwxIMUOhQcKsAlvWczSi1g
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"elasticsearch.k8s.elastic.co/v1","kind":"Elasticsearch","metadata":{"annotations":{},"name":"quickstart","namespace":"default"},"spec":{"nodeSets":[{"config":{"node.store.allow_mmap":false},"count":2,"name":"elastic-node"}],"version":"8.17.3"}}
    creationTimestamp: "2025-03-23T22:11:14Z"
    generation: 2
    name: quickstart
    namespace: default
    resourceVersion: "688226"
    uid: 2b3e228c-5773-4354-9bc1-809b5927a4c3
  spec:
    auth: {}
    http:
      service:
        metadata: {}
        spec: {}
      tls:
        certificate: {}
    monitoring:
      logs: {}
      metrics: {}
    nodeSets:
    - config:
        node.store.allow_mmap: false
      count: 2
      name: elastic-node
      podTemplate:
        metadata:
          creationTimestamp: null
        spec:
          containers: null
    remoteClusterServer: {}
    transport:
      service:
        metadata: {}
        spec: {}
      tls:
        certificate: {}
        certificateAuthorities: {}
    updateStrategy:
      changeBudget: {}
    version: 8.17.3
  status:
    availableNodes: 2
    conditions:
    - lastTransitionTime: "2025-03-23T22:13:25Z"
      status: "True"
      type: ReconciliationComplete
    - lastTransitionTime: "2025-03-23T22:11:16Z"
      message: All nodes are running version 8.17.3
      status: "True"
      type: RunningDesiredVersion
    - lastTransitionTime: "2025-03-23T22:13:25Z"
      message: Service default/quickstart-es-internal-http has endpoints
      status: "True"
      type: ElasticsearchIsReachable
    - lastTransitionTime: "2025-03-23T22:11:16Z"
      message: 'Cannot get compute and storage resources from Elasticsearch resource
        generation 2: cannot compute resources for NodeSet "elastic-node": no CPU
        request or limit set'
      status: "False"
      type: ResourcesAwareManagement
    health: green
    inProgressOperations:
      downscale:
        lastUpdatedTime: "2025-03-23T22:11:16Z"
      upgrade:
        lastUpdatedTime: "2025-03-23T22:11:16Z"
      upscale:
        lastUpdatedTime: "2025-03-23T22:11:16Z"
    observedGeneration: 2
    phase: Ready
    version: 8.17.3
kind: List
metadata:
  resourceVersion: ""
