apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: web-servers-1
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts: 
      - mountPath: /home
        name: diretorio
    resources: 
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
    - name: diretorio
      emptyDir: 
        sizeLimit: 256Mi
status: {}
